server:
  port: 8888

spring:
  application:
    name: configuration-server
  profiles:
    active: native

application:
  default:
    currency: USD

---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/
