apiVersion: v1
kind: ConfigMap
metadata:
  name: yas-configuration-configmap
  annotations:
    reloader.stakater.com/match: "true"
data:
  application.yaml: |
    {{- toYaml .Values.applicationConfig | nindent 4 }}
  logback.xml: |
    {{- .Values.logbackConfig | nindent 4 }}